import { Employee } from "../Types/Employee";
const yestedayDate = () => {
    let date = new Date();
    return date.setDate(date.getDate() - 1);
};

export const mockEmployees: Employee[] = [
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 55555,
        state: "France",
        city: "Bordeaux",
        street: "49 rue des Corbeaux",
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date ("1990-05-05"),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 254651,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 444444,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 111111,
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "14",
        firstName: "Charles",
        lastName: "Jude",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 333333,
        state: "Croatie",
        city: "Quelquepart",
        street: "Par la bas",
        department: "justdoit",
    },
    {
        id: "15",
        firstName: "Oui",
        lastName: "Eston",
        dateOfBirth: new Date(),
        startDate: new Date(),

        zipCode: 22222,
        state: "Italy",
        city: "Napoli",
        street: "79 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Franc",
        lastName: "Rivenzi",
        dateOfBirth: new Date(yestedayDate()),
        startDate: new Date(yestedayDate()),

        zipCode: 111111,
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Franc",
        lastName: "rivenzi",
        dateOfBirth: new Date(yestedayDate()),
        startDate: new Date(yestedayDate()),

        zipCode: 111111,
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
];
