import { Employee } from "../Types/Employee";

export const mockEmployees: Employee[] = [
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 55555,
            state: "France",
            city: "Bordeaux",
            street: "49 rue des Corbeaux",
        },
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        birthDate: new Date(),
        startDate: new Date(),
        adress: {
            zipCode: 254651,
            state: "Italy",
            city: "Napoli",
            street: "49 strada del parmigiano",
        },
        department: "humanR",
    },
];
