import { Employee } from "../Types/Employee";
// const yestedayDate = () => {
//     let date = "2022-11-06";
//     return date.setDate(date.getDate() - 1);
// };

export const mockEmployees: Employee[] = [
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "96542",
        state: "France",
        city: "Bordeaux",
        street: "49 rue des Corbeaux",
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "98422",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "66326",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "35874",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Etienne",
        lastName: "Villier",
        dateOfBirth: "1995-01-25",
        startDate: "2022-11-06",

        zipCode: "654425",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "444444",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "111111",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "14",
        firstName: "Charles",
        lastName: "Jude",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "333333",
        state: "Croatie",
        city: "Quelquepart",
        street: "Par la bas",
        department: "justdoit",
    },
    {
        id: "15",
        firstName: "Oui",
        lastName: "Eston",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "22222",
        state: "Italy",
        city: "Napoli",
        street: "79 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Romuald",
        lastName: "Lafrange",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "17",
        firstName: "Pierre",
        lastName: "Vidange",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "11111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-22",

        zipCode: "572727",
        state: "France",
        city: "Bordeaux",
        street: "49 rue des Corbeaux",
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-22",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-07-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-07-21",
        startDate: "2022-08-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-08-21",
        startDate: "2022-08-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-08-21",
        startDate: "2022-08-21",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-08-21",
        startDate: "2022-08-21",

        zipCode: "154156",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-08-21",
        startDate: "2021-08-25",

        zipCode: "111111",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "14",
        firstName: "Charles",
        lastName: "Jude",
        dateOfBirth: "2021-08-25",
        startDate: "2021-08-25",

        zipCode: "333333",
        state: "Croatie",
        city: "Quelquepart",
        street: "Par la bas",
        department: "justdoit",
    },
    {
        id: "15",
        firstName: "Oui",
        lastName: "Eston",
        dateOfBirth: "2021-08-25",
        startDate: "2021-08-25",

        zipCode: "22222",
        state: "Italy",
        city: "Napoli",
        street: "79 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Franc",
        lastName: "Rivenzi",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "17",
        firstName: "Franc",
        lastName: "rivenzi",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        dateOfBirth: "2021-08-25",
        startDate: "2021-08-25",

        zipCode: "55555",
        state: "France",
        city: "Bordeaux",
        street: "49 rue des Corbeaux",
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-08-25",
        startDate: "2021-08-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-08-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-07-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-07-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-07-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "22 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-07-25",
        startDate: "2021-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2021-07-25",
        startDate: "1992-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "335465",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "4616161",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "14",
        firstName: "Charles",
        lastName: "Jude",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "333333",
        state: "Croatie",
        city: "Quelquepart",
        street: "Par la bas",
        department: "justdoit",
    },
    {
        id: "15",
        firstName: "Oui",
        lastName: "Eston",
        dateOfBirth: "1992-07-25",
        startDate: "1992-07-25",

        zipCode: "22222",
        state: "Italy",
        city: "Napoli",
        street: "79 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Franc",
        lastName: "Rivenzi",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "17",
        firstName: "Franc",
        lastName: "rivenzi",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "1",
        firstName: "joe",
        lastName: "Rigga",
        dateOfBirth: "1992-07-25",
        startDate: "1995-01-25",

        zipCode: "55555",
        state: "France",
        city: "Bordeaux",
        street: "49 rue des Corbeaux",
        department: "affair",
    },
    {
        id: "2",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "3",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "4",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "5",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "6",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "7",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "8",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "9",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "10",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "11",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "254651",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "12",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "1995-01-25",
        startDate: "1995-01-25",

        zipCode: "5461616",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "13",
        firstName: "Carole",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "111111",
        state: "Italy",
        city: "Napoli",
        street: "49 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "14",
        firstName: "Charles",
        lastName: "Jude",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "333333",
        state: "Croatie",
        city: "Quelquepart",
        street: "Par la bas",
        department: "justdoit",
    },
    {
        id: "15",
        firstName: "Oui",
        lastName: "Eston",
        dateOfBirth: "2022-11-06",
        startDate: "2022-11-06",

        zipCode: "22222",
        state: "Italy",
        city: "Napoli",
        street: "79 strada del parmigiano",
        department: "humanR",
    },
    {
        id: "16",
        firstName: "Xavier",
        lastName: "Nourisson",
        dateOfBirth: "1995-01-25",
        startDate: "2013-01-25",

        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
    {
        id: "17",
        firstName: "Fabien",
        lastName: "Delmar",
        dateOfBirth: "1950-01-25",
        startDate: "1995-01-25",
        zipCode: "111111",
        state: "USA",
        city: "New-York",
        street: "23 aloalo",
        department: "humanR",
    },
];
